# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-25 11:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigMaster',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hypervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(max_length=50)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HypervisorReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2018, 5, 25, 11, 40, 32, 815584, tzinfo=utc))),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('total_memory', models.FloatField()),
                ('total_cpu', models.FloatField()),
                ('total_disk', models.FloatField()),
                ('used_memory', models.FloatField()),
                ('used_cpu', models.FloatField()),
                ('used_disk', models.FloatField()),
                ('hypervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Hypervisor')),
            ],
        ),
        migrations.CreateModel(
            name='HypervisorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypervisor_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('has_access', models.BooleanField(default=False)),
                ('hypervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Hypervisor')),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=255)),
                ('instance_id', models.CharField(blank=True, max_length=255, null=True)),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('doc', models.DateField()),
                ('doe', models.DateField()),
                ('flavor', models.CharField(max_length=255)),
                ('network', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('requested', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('hypervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Hypervisor')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2018, 5, 25, 11, 40, 32, 816311, tzinfo=utc))),
                ('total_hours', models.FloatField()),
                ('total_memory', models.FloatField()),
                ('total_cpu', models.FloatField()),
                ('total_disk', models.FloatField(blank=True, null=True)),
                ('used_memory', models.FloatField()),
                ('used_cpu', models.FloatField()),
                ('used_disk', models.FloatField()),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Project')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email_id', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('default_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Project')),
            ],
        ),
        migrations.CreateModel(
            name='UserCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, null=True)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('hypervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Hypervisor')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.User')),
            ],
        ),
        migrations.CreateModel(
            name='VMReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2018, 5, 25, 11, 40, 32, 816865, tzinfo=utc))),
                ('total_hours', models.FloatField()),
                ('total_memory', models.FloatField()),
                ('total_cpu', models.FloatField()),
                ('total_disk', models.FloatField(blank=True, null=True)),
                ('used_memory', models.FloatField()),
                ('used_cpu', models.FloatField()),
                ('used_disk', models.FloatField()),
                ('instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Instance')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Project')),
            ],
        ),
        migrations.AddField(
            model_name='instance',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Project'),
        ),
        migrations.AddField(
            model_name='instance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.User'),
        ),
        migrations.AddField(
            model_name='hypervisoruser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.User'),
        ),
    ]
