# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-05 11:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hypervisorreport',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 5, 11, 19, 16, 936791, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 5, 11, 19, 16, 937415, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vmreport',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 5, 11, 19, 16, 938044, tzinfo=utc)),
        ),
    ]
