# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-05 12:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20180605_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hypervisorreport',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 5, 12, 36, 15, 717118, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 5, 12, 36, 15, 717754, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vmreport',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 5, 12, 36, 15, 718426, tzinfo=utc)),
        ),
    ]
