# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-06 04:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20180605_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hypervisorreport',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 6, 4, 52, 52, 12748, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 6, 4, 52, 52, 13381, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vmreport',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 6, 4, 52, 52, 14015, tzinfo=utc)),
        ),
    ]
