# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-12 11:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20180606_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hypervisorreport',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 11, 57, 29, 404658, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 11, 57, 29, 405313, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vmreport',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 11, 57, 29, 405879, tzinfo=utc)),
        ),
    ]
