FROM ubuntu:14.04
MAINTAINER Sanket Modi "sanket.modi@gslab.com"
RUN apt-get update && apt-get -y upgrade --fix-missing
RUN apt-get install -y python python-dev python-pip libmysqlclient-dev build-essential libssl-dev libffi-dev libsasl2-dev libldap2-dev
COPY requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt
RUN apt-get install -y git
RUN apt-get install -y apache2
RUN apt-get install -y apache2-dev
RUN sudo apt-get install libapache2-mod-wsgi
RUN sudo a2enmod wsgi